### ISSUE TITLE
Marker Cluster and Lasso 

### ISSUE THREAD

**Issue by bwaltersjr616** [zakjan/leaflet-lasso#43] opened 2021-12-16 17:45 UTC
I am running into intermittent issue when selecting a cluster, single markers work ok.   When selecting a cluster Im getting ...

Uncaught TypeError: Cannot read properties of undefined (reading '_content')
mouseup event was missed  (lasso-handler.ts:134)

here is my code in creating the layer...

    function createMarkerLayer(layerName, groupName, dataMatrix) {
        var markers = new L.markerClusterGroup({
		maxClusterRadius:30
		});
		var markerList = [];
        $.each(dataMatrix, function(i) {
		
		var splitData = dataMatrix[i][0].qText.split("|");
		var a = splitData[1].split(",");
		if (a[0] !== "" || a[1] !== "") {
		var title = splitData[2] + "<br>" + splitData[0] + "<br>" + layerName;
		var marker = L.marker(L.latLng(a[1], a[0]), { title: title });
		marker.bindPopup(title);
		markerList.push(marker);
		}
        });

		markers.addLayers(markerList);
		control.addOverlay( markers, layerName, {groupName : groupName, expanded: true} );
	
    }

Any help would be greatly appreciated.

**Comment by zakjan** [comment] 2021-12-17 09:50
Hi, the warning "mouseup event was missed" is usually triggered when another component prevents propagating mouse events. Do you use any other plugins?

**Comment by bwaltersjr616** [comment] 2021-12-17 19:08
I do.  I am also using the styledLayerControl.

**Comment by zakjan** [comment] 2022-05-03 21:38
Closing, because this is not a bug in this library. "mouseup event was missed" is a warning that another part of the application caught mouseup event, and potentially might need to be investigated in the application.

**Closed as completed by zakjan** 2022-05-03 21:38 UTC
